apiVersion: v1
kind: Pod
metadata:
  name: liveness-test
  labels:
    test: liveness
spec:
  containers:
    - name: liveness-test-container
      image: zubayear/kubernetes-experiment:1.1.1
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /hello
          port: 8080
        initialDelaySeconds: 15 # kubelet should wait 15s before performing the first probe
        timeoutSeconds: 2
        periodSeconds: 5 # kubelet should perform a liveness probe every 5 seconds
        failureThreshold: 1
# kubectl apply -f probe.pod.yml
# kubectl describe pod [pod-name]
# kubectl exec [pod-name] -i -t -- sh
# kubectl port-forward [pod-name] curl-port:internal-port
